### ISSUE TITLE
"Search this name" helyett "Search "Balazs Paroczay""

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#10]
Megoldható, hogy a jobb gombnál lévő szöveg a kijelölt szöveget mutassa? 

mint pl. a search "balazs Paroczay" on Google esetében 

![Screenshot 2022-09-09 at 16 48 23](https://user-images.githubusercontent.com/33448047/189378436-049b93a4-f944-4c8c-8816-613faf09bddb.png)

**Comment by GuBee33** [comment]
Sajnos nem, mert a menü akkor rederelődik mikor az extension betölt...

**Comment by GuBee33** [comment]
Max olyat lehet hogy search for the selected test de sajnos a kijelölt szöveg nem tud megjelenni

**Comment by GuBee33** [comment]
sajnos ez nem megvalósítható
