### ISSUE TITLE
+1 keyword?

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#11]
megoldható-e lenne, hogy még egy (pár?) keyword-öt beletegyen ebbe a keresésbe? 

pl. kijelöli a nevet és utána ír még vmit? vhova?

**Comment by GuBee33** [comment]
gondolkoztam már ezen, még nem találtam rá megoldást

**Comment by GuBee33** [comment]
Van egy jó ötletem!!!
