### ISSUE TITLE
Lassú frissülés

### ISSUE THREAD

**Issue by Vinceszy** [GuBee33/Code---chrome-extension#15]
Ha elmentek egy új variationt, a legördülő menüben nem jelenik meg oldal frissítés után sem, csak ha újraindítom a böngészőt (Chrome). Illetve ott vannak a már kitörölt mentések is (mint a név nélküli, és a próba a képen).

![Screenshot 2022-09-09 at 22 30 35](https://user-images.githubusercontent.com/5405831/189438105-da4af3e0-6afa-4773-9ddf-1e0ff0ddddaa.png)

**Comment by GuBee33** [comment]
sajnos ezt nem lehet megoldani. az extensiont kell frissíteni vagy a böngészőt újraindítani. A menu akkor  generálódik amikor az extension betőlt
