### ISSUE TITLE
nem távolítja el a korábbi mentett socmed option selection-t 

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#18]
elmentettem egy option-t, eleneveztem GFB-nek, majd rájöttem, hogy nem kell mégse, delete all és csináltam egy újat (IT) 

nem távolítja el a GFB-t a jobb gombos részről (és nem is csinál semmit, ha ráklikkelek)

<img width="1091" alt="Screenshot 2022-09-10 at 10 55 33" src="https://user-images.githubusercontent.com/33448047/189476436-20253ed5-320c-4e63-b491-599bab6c3e30.png">

**Comment by GuBee33** [comment]
Sajnos mivel a menüt akkor generálja mikor az extension betölt, ezért vagy az extensionre kell egy refresh-t nyomni vagy a böngészőt bezárni/újra megnyitni :(
