### ISSUE TITLE
adjuk hozzá a Reddit-et is! 

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#20]
sorrendben legyen a github után!

Nickname
https://www.reddit.com/user/nickname/

Full name
https://www.google.com/search?q=site%3Areddit.com%2Fuser%2F+-inurl%3Acomments+%22Full name%22

**Comment by GuBee33** [comment]
keyword keresés?

**Comment by thebalazs** [comment]
jó kérdés, ez nem kell! csak nickname és Full name
