### ISSUE TITLE
adjuk hozzá a TikTok-ot! 

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#21]
nickname
https://www.google.com/search?q=site%3Atiktok.com+intitle%3A%22nickname%22

Full name
https://www.google.com/search?q=site%3Atiktok.com+%22full name%22

**Comment by GuBee33** [comment]
extra kulcsszavas keresés?

**Comment by thebalazs** [comment]
és itt se kell kw

**Comment by thebalazs** [comment]
eggyel több "" lett az intitle: után - ki tudod, kérlek, szedni? 

<img width="773" alt="Screenshot 2022-09-11 at 0 13 10" src="https://user-images.githubusercontent.com/33448047/189503567-26b2754f-dfaf-4053-9657-63ea758a0fc5.png">

**Comment by GuBee33** [comment]
https://github.com/THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE itt folytatódik. 0.0.0.6-ban benne lesz
