### ISSUE TITLE
platform order (default)

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#22]
LinkedIn
Xing
Google
Twitter
Facebook
Instagram
TikTok
Github
Reddit

(és így kéne őket írni, ne kisbetűvel)

**Comment by GuBee33** [comment]
arra gondoltam megnézem hogy tudok e logot tenni :) azért az menőbb lenne

**Comment by thebalazs** [comment]
woohoooo, de gyönyörű lenne úgy! 

a sorrend azta  logikát követi, h 
1) professzionális networkök
2) google
3) nagy social
4) IT
