### ISSUE TITLE
be tudjuk-e vinni a Chrome Extension Store-ba?

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#25]
be tudjuk-e vinni a Chrome Extension Store-ba?

mi a menete ennek?

**Comment by GuBee33** [comment]
done
https://chrome.google.com/webstore/detail/code-candidate-lookup-too/ibfmahfoaohgpmfpklfkppmgpkjomked?hl=en&authuser=0

**Comment by thebalazs** [comment]
köszönöm!!!
