### ISSUE TITLE
(nem issue, hagyjuk open) milyen social media kellhet még? listázzuk!

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#26]
kaggle
behance 
gitlab
snapchat (site:snapchat.com/ john)
telegram (?)

már kértem: reddit, tiktok

**Comment by GuBee33** [comment]
Mit szólnátok ha ez az option-ben lenne és ott lehetne updatelni a listát és nem kellene akkor új release? 
Illetve ha változik az URL akkor is elég a configot módosítani.

**Comment by thebalazs** [comment]
ezt nem értem - mmint tegyünk bele mindent az option-be? 

igen, ezt azért nyitottam, hogy Vince és Kata még tudjon ezen agyalni

**Comment by GuBee33** [comment]
úgy értem hogy lehessen a listát szerkeszteni és ne csak beégetve legyenek meg az URL-ek

**Comment by thebalazs** [comment]
legyen a Medium is! :)

https://www.google.com/search?q=site%3Amedium.com%2F+intitle%3A%22full name%22 (nem kell kulcsszó!)
https://medium.com/@nickname

**Comment by thebalazs** [comment]
és mehet a youtube is :) 

full Name
site:youtube.com/ intitle:"full name" -inurl:watch

nickname
https://www.youtube.com/c/nickname

logo
https://www.pinterest.com/pin/793337290594260546/sent/?invite_code=c71d55aabf7b426ab870bf33bc1edf89&sfo=1

**Comment by thebalazs** [comment]
ezt át tudod mozgatni a CODE alá, Tomi?

**Comment by Vinceszy** [comment]
nicknamenek:
https://namechk.com/

Itt az URL baromi ronda, mert a végén van egy captcha confirm code. Ha esetleg van rá megoldás hogy egyben oda is generáljunk egy fasza kódot az király, ha nem, akkor a user kattintja majd azt.

https://namechk.com/namechk-plugin-search-results/?n=gubee33&g-recaptcha-response=03ANYolqtGt2-XrNPy10DS7YztUVhi-RAMJSCve4EgUb-kKJXvMpZTJwfNeA4MAzrMhydx_qaRJQlW3ZdUc3j7p4gDRNY9PRONqqwmPoSo-Ep26HE_5xEk018N4ZQudpcpOJuq1TbIlRQGOLLsRQwsxbkdZZL0zHBWrMgU2GLMLj-UgGsrM1CDqFslwml8Q_u7BgcfIOjs6SjP-BwsuHeZxnLY0JwFc85Q7CQzGY6sw1zhM1y_-t75afns_Mg7MG2z_lmFoHjSXpVGaDIw4qAWV1iWMqovIGcf2O9QrKF1eSQDtB0kgnkuM-Wz_yM7mkcFBJg9rgb0z5pE63OQxHf9yIHWARFOnlguGsRm6OeYrGTVRVXNRNuPcj4k_ld4JWHpbDMth5zk5oow6y526yulp2EJD50Jw7WSfKaAxvYv4DFk6xGOoSjxiBvCNoWve8MYnQ-7JIvZBTJPXS5AI2vLOnsk189SEJ-GUCBJNoFLI-75ty0zq-guJzy2ldntlg0EJLV3TDWHvcHYWZFzKcHuUPfD0nHPqjWQfuyCiDLEMPtf3eWSHLwXW7LQS2Tdoa00jjnhAODPweaYdOzAv2l-DnvmujWXu1s14g

**Comment by GuBee33** [comment]
> nicknamenek: https://namechk.com/
> 
> Itt az URL baromi ronda, mert a végén van egy captcha confirm code. Ha esetleg van rá megoldás hogy egyben oda is generáljunk egy fasza kódot az király, ha nem, akkor a user kattintja majd azt.
> 
> https://namechk.com/namechk-plugin-search-results/?n=gubee33&g-recaptcha-response=03ANYolqtGt2-XrNPy10DS7YztUVhi-RAMJSCve4EgUb-kKJXvMpZTJwfNeA4MAzrMhydx_qaRJQlW3ZdUc3j7p4gDRNY9PRONqqwmPoSo-Ep26HE_5xEk018N4ZQudpcpOJuq1TbIlRQGOLLsRQwsxbkdZZL0zHBWrMgU2GLMLj-UgGsrM1CDqFslwml8Q_u7BgcfIOjs6SjP-BwsuHeZxnLY0JwFc85Q7CQzGY6sw1zhM1y_-t75afns_Mg7MG2z_lmFoHjSXpVGaDIw4qAWV1iWMqovIGcf2O9QrKF1eSQDtB0kgnkuM-Wz_yM7mkcFBJg9rgb0z5pE63OQxHf9yIHWARFOnlguGsRm6OeYrGTVRVXNRNuPcj4k_ld4JWHpbDMth5zk5oow6y526yulp2EJD50Jw7WSfKaAxvYv4DFk6xGOoSjxiBvCNoWve8MYnQ-7JIvZBTJPXS5AI2vLOnsk189SEJ-GUCBJNoFLI-75ty0zq-guJzy2ldntlg0EJLV3TDWHvcHYWZFzKcHuUPfD0nHPqjWQfuyCiDLEMPtf3eWSHLwXW7LQS2Tdoa00jjnhAODPweaYdOzAv2l-DnvmujWXu1s14g

nem lehet kódból legenerálni azt hogy nem vagyok robot :) ez a lényeg benne :)

**Comment by GuBee33** [comment]
Új repoban done
