### ISSUE TITLE
Xing logo

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#28]
Tomi, kérlek, használd ezt, és akkor egységes lesz teljesen a többi logóval 

https://www.iconpacks.net/icons/2/free-xing-logo-icon-2447-thumb.png

**Comment by GuBee33** [comment]
https://github.com/THE-SOURCE-CODE-AGENCY/Candidate-Lookup-by-CODE itt folytatódik. 0.0.0.6-ban benne lesz
