### ISSUE TITLE
Options sorrend vs. page order sorrend

### ISSUE THREAD

**Issue by thebalazs** [GuBee33/Code---chrome-extension#9]
![Screenshot 2022-09-09 at 16 46 04](https://user-images.githubusercontent.com/33448047/189377866-fda3aa5b-2339-4ee9-984d-3db89936fbd4.png)

pont fordított osrrendben nyitja meg a lapokat, mint ami az Options dobozban van. az első a LIN kéne, hogy legyen stb.

**Comment by GuBee33** [comment]
az új feater megoldja
